# Spark Monitoring Configuration for Airflow DAGs

# Monitoring Settings
monitoring:
  enabled: true
  sample_interval: 1.0  # seconds
  save_metrics: true
  output_directory: "monitoring_results"
  
# Spark Configuration for Monitoring
spark:
  # Basic Settings
  app_name: "EnhancedBDTransformer"
  master: "local[*]"  # Change to "yarn" or "spark://host:port" for cluster
  
  # Memory Settings
  driver_memory: "4g"
  executor_memory: "4g"
  driver_max_result_size: "2g"
  
  # Parallelism Settings
  default_parallelism: 150
  sql_shuffle_partitions: 120
  
  # Serialization Settings
  kryoserializer_buffer_max: "512m"
  kryoserializer_buffer: "64k"
  
  # Adaptive Query Execution
  sql_adaptive_enabled: "true"
  sql_adaptive_coalesce_partitions_enabled: "true"
  sql_adaptive_skew_join_enabled: "true"
  sql_adaptive_local_shuffle_reader_enabled: "true"
  
  # Event Logging (for Spark UI)
  event_log_enabled: "true"
  event_log_dir: "/tmp/spark-events"
  history_fs_log_directory: "/tmp/spark-events"
  
  # UI Settings
  ui_port: 4040
  ui_retained_jobs: 100
  ui_retained_stages: 100
  
  # Dynamic Allocation (for YARN)
  dynamic_allocation_enabled: "false"
  dynamic_allocation_min_executors: 1
  dynamic_allocation_max_executors: 10
  dynamic_allocation_initial_executors: 1

# Performance Thresholds
thresholds:
  cpu_usage:
    warning: 80.0  # percentage
    critical: 95.0
  memory_usage:
    warning: 80.0  # percentage
    critical: 95.0
  execution_time:
    warning: 300.0  # seconds
    critical: 600.0
  spark_stages:
    failed_threshold: 0  # number of failed stages
    success_rate_min: 0.95  # minimum success rate

# Alerting Settings
alerts:
  enabled: true
  email_notifications: false
  slack_notifications: false
  webhook_url: ""
  
# Data Quality Checks
data_quality:
  enabled: true
  check_null_percentage: true
  null_threshold: 0.1  # 10% null values threshold
  check_data_types: true
  check_value_ranges: true

# Output Settings
output:
  save_transformed_data: true
  save_inversed_data: true
  save_monitoring_data: true
  compression: "snappy"  # parquet compression
  format: "parquet" 